combine_control_expr = false
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
edition = "2021"
fn_single_line = true
hard_tabs = true
imports_layout = "HorizontalVertical"
match_arm_leading_pipes = "Preserve"
imports_granularity = "Crate"
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
where_single_line = true
